"""Generate a reproducible deployment package from a sweep.

The package is the point of the whole exercise: a directory someone can read,
run, containerise, and check, without needing ArmForge installed or trusting
any claim in it. It contains the configuration that won, the evidence it won
on, and the exact commands to reproduce both.

The model file itself is *not* copied. It is referenced by path, size and
content hash. Copying multi-gigabyte weights into every export would make the
package unusable, and a hash lets the consumer verify they have the same
artifact the measurements describe.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .. import __version__
from . import html as html_report

if TYPE_CHECKING:  # pragma: no cover
    from ..optimize.recommend import Recommendation
    from ..optimize.sweep import SweepReport

#: Read in chunks so hashing a large model does not load it into memory.
_HASH_CHUNK = 1024 * 1024


def content_hash(path: Path, *, max_bytes: int | None = None) -> str | None:
    """SHA-256 of a file, truncated for readability.

    ``max_bytes`` hashes only a prefix, which keeps export fast for very large
    weights. The digest is labelled with what it covers so it is never mistaken
    for a whole-file hash.
    """
    digest = hashlib.sha256()
    read = 0
    try:
        with path.open("rb") as handle:
            while chunk := handle.read(_HASH_CHUNK):
                if max_bytes is not None and read + len(chunk) > max_bytes:
                    digest.update(chunk[: max_bytes - read])
                    read = max_bytes
                    break
                digest.update(chunk)
                read += len(chunk)
    except OSError:
        return None
    prefix = "sha256" if max_bytes is None or read < max_bytes else f"sha256-first{read}"
    return f"{prefix}:{digest.hexdigest()[:32]}"


def _config(report: SweepReport, rec: Recommendation, model_hash: str | None) -> dict[str, Any]:
    config = rec.winner.result.config
    cpu = report.host.cpu

    return {
        "armforge_version": __version__,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "objective": rec.objective.value,
        "model": {
            "path": config.model.path,
            "quantization": config.model.quantization,
            "size_bytes": config.model.size_bytes,
            "parameters": config.model.n_params,
            "content_hash": model_hash,
        },
        "runtime": {
            "name": config.runtime.name,
            "label": config.runtime.label,
            "version": config.runtime.version,
            "build_flags": dict(config.runtime.build_flags),
        },
        "threads": {
            "generation": rec.decode.threads if rec.decode else None,
            "batch": rec.prefill.threads if rec.prefill else None,
        },
        "command": rec.deployment_command,
        "measured_on": {
            "cpu": cpu.model,
            "architecture": cpu.architecture,
            "physical_cores": cpu.physical_cores,
            "heterogeneous": cpu.is_heterogeneous,
            "arm_features": sorted(cpu.features),
            "sve_vector_bits": cpu.sve_vector_bits,
            "sme_vector_bits": cpu.sme_vector_bits,
            "os": f"{report.host.os_name} {report.host.os_release}".strip(),
        },
        "measured": {
            "workload": config.workload.to_dict(),
            "iterations": config.iterations,
            "prefill_tok_s": rec.prefill.throughput if rec.prefill else None,
            "decode_tok_s": rec.decode.throughput if rec.decode else None,
            "peak_memory_bytes": rec.winner.result.peak_memory_bytes,
        },
        "improvements_vs_nproc_baseline_pct": rec.improvements,
        "caveats": list(rec.warnings),
    }


def _run_script(rec: Recommendation) -> str:
    config = rec.winner.result.config
    generation = rec.decode.threads if rec.decode else None
    batch = rec.prefill.threads if rec.prefill else None

    return f"""#!/usr/bin/env bash
# Generated by ArmForge {__version__}.
#
# The two thread counts differ because the two phases of inference are bound
# by different resources on the CPU this was measured on:
#   -t  {generation}  token generation   (memory-bandwidth-bound)
#   -tb {batch}  prompt processing (compute-bound)
#
# Every value is overridable by environment variable:
#   ARMFORGE_MODEL              path to the .gguf weights
#   LLAMA_BIN                   llama.cpp binary to use
#   ARMFORGE_THREADS_GENERATION -t
#   ARMFORGE_THREADS_BATCH      -tb

set -euo pipefail

MODEL="${{ARMFORGE_MODEL:-{config.model.path}}}"
LLAMA_BIN="${{LLAMA_BIN:-llama-completion}}"
THREADS_GENERATION="${{ARMFORGE_THREADS_GENERATION:-{generation or ""}}}"
THREADS_BATCH="${{ARMFORGE_THREADS_BATCH:-{batch or ""}}}"

if [[ ! -f "$MODEL" ]]; then
    echo "error: model not found at $MODEL" >&2
    echo "set ARMFORGE_MODEL to its location" >&2
    exit 1
fi

if ! command -v "$LLAMA_BIN" >/dev/null 2>&1 && [[ ! -x "$LLAMA_BIN" ]]; then
    echo "error: $LLAMA_BIN not found; set LLAMA_BIN to your llama.cpp binary" >&2
    exit 1
fi

args=(-m "$MODEL")
# Written as if-blocks rather than `[[ ... ]] && args+=(...)`: under `set -e`
# a false test makes the whole statement return non-zero and the script would
# exit silently.
if [[ -n "$THREADS_GENERATION" ]]; then
    args+=(-t "$THREADS_GENERATION")
fi
if [[ -n "$THREADS_BATCH" ]]; then
    args+=(-tb "$THREADS_BATCH")
fi

exec "$LLAMA_BIN" "${{args[@]}}" "$@"
"""


def _dockerfile(report: SweepReport, rec: Recommendation) -> str:
    config = rec.winner.result.config
    generation = rec.decode.threads if rec.decode else 4
    batch = rec.prefill.threads if rec.prefill else 4
    commit = config.runtime.version
    flags = config.runtime.build_flags
    kleidiai = "ON" if flags.get("kleidiai") else "OFF"
    model_name = Path(config.model.path).name

    return f"""# Generated by ArmForge {__version__}.
#
# Build for Arm64:
#     docker build --platform linux/arm64 -t armforge-inference .
#
# A container does not make anything faster. This image exists so the
# measured configuration -- the same llama.cpp commit, the same build flags,
# the same per-phase thread counts -- can be reproduced exactly. The
# performance comes from those choices, not from Docker.
#
# The model is not baked in. Mount it at run time:
#     docker run --rm -v /path/to/models:/models \\
#         -e ARMFORGE_MODEL=/models/{model_name} armforge-inference

FROM --platform=linux/arm64 debian:bookworm-slim AS build

RUN apt-get update && apt-get install -y --no-install-recommends \\
        build-essential cmake git ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
RUN git clone https://github.com/ggml-org/llama.cpp.git . \\
    && git checkout {commit}

# These flags are what ArmForge measured. Changing them invalidates the
# benchmark results in this package.
RUN cmake -B build \\
        -DCMAKE_BUILD_TYPE=Release \\
        -DGGML_METAL=OFF \\
        -DGGML_CPU_KLEIDIAI={kleidiai} \\
        -DLLAMA_BUILD_TESTS=OFF \\
        -DLLAMA_BUILD_EXAMPLES=OFF \\
        -DLLAMA_BUILD_SERVER=OFF \\
    && cmake --build build --target llama-completion -j "$(nproc)"

FROM --platform=linux/arm64 debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
        libgomp1 ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

# llama.cpp puts its shared libraries alongside the binaries, so one copy
# takes both and LD_LIBRARY_PATH points the loader at them.
COPY --from=build /src/build/bin/ /usr/local/lib/llama/
COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

ENV LD_LIBRARY_PATH=/usr/local/lib/llama \\
    ARMFORGE_MODEL=/models/{model_name} \\
    LLAMA_BIN=/usr/local/lib/llama/llama-completion \\
    ARMFORGE_THREADS_GENERATION={generation} \\
    ARMFORGE_THREADS_BATCH={batch}

ENTRYPOINT ["/usr/local/bin/run.sh"]
"""


def _readme(report: SweepReport, rec: Recommendation, model_hash: str | None) -> str:
    config = rec.winner.result.config
    cpu = report.host.cpu
    generation = rec.decode.threads if rec.decode else None
    batch = rec.prefill.threads if rec.prefill else None

    lines = [
        f"# Optimised deployment — {config.model.quantization} on {cpu.model}",
        "",
        "Generated by [ArmForge](https://github.com/36taransingh5-dotcom/armForge) "
        f"{__version__} from measurements taken on this machine. Every figure "
        "below was benchmarked; none is estimated.",
        "",
        "## The configuration",
        "",
        "| | |",
        "| --- | --- |",
        f"| Model | `{Path(config.model.path).name}` |",
        f"| Quantisation | **{config.model.quantization}** |",
        f"| Runtime | {config.runtime.label} (`{config.runtime.version}`) |",
    ]
    if batch:
        lines.append(f"| Prompt-processing threads (`-tb`) | **{batch}** |")
    if generation:
        lines.append(f"| Generation threads (`-t`) | **{generation}** |")
    if model_hash:
        lines.append(f"| Model hash | `{model_hash}` |")
    lines += [
        "",
        "```bash",
        rec.deployment_command,
        "```",
        "",
    ]

    if batch and generation and batch != generation:
        lines += [
            f"The two thread counts differ deliberately. Prompt processing is "
            f"compute-bound and peaks at {batch} threads; token generation is "
            f"bound by memory bandwidth and peaks at {generation}. llama.cpp "
            "accepts them separately, so both are set rather than averaging "
            "them into one number that is wrong for each phase.",
            "",
        ]

    # -- measured ---------------------------------------------------------
    lines += ["## What was measured", "", "| Metric | Value |", "| --- | ---: |"]
    if rec.prefill:
        lines.append(
            f"| Prompt processing | {rec.prefill.throughput:.1f} tok/s "
            f"(± {rec.prefill.stddev:.1f}) |"
        )
    if rec.decode:
        lines.append(
            f"| Token generation | {rec.decode.throughput:.1f} tok/s "
            f"(± {rec.decode.stddev:.1f}) |"
        )
    if rec.winner.result.peak_memory_bytes:
        lines.append(
            f"| Peak resident memory | "
            f"{rec.winner.result.peak_memory_bytes / 1024**2:.0f} MiB |"
        )
    lines += [
        f"| Workload | {config.workload.name} — "
        f"{config.workload.prompt_tokens} prompt / "
        f"{config.workload.generate_tokens} generated tokens |",
        f"| Repetitions | {config.iterations} |",
        "",
    ]

    if rec.reasons:
        lines += ["### Why this configuration won", ""]
        lines += [f"- {reason}" for reason in rec.reasons]
        lines.append("")

    if rec.baseline is not None:
        base = rec.baseline.config
        lines += [
            f"Improvements are stated against the naive default: "
            f"{base.threads} threads (what `nproc` reports) with "
            f"{base.model.quantization} on an unmodified build — what a "
            "developer would land on without measuring.",
            "",
        ]

    if rec.warnings:
        lines += ["### Caveats", ""]
        lines += [f"- {warning}" for warning in rec.warnings]
        lines.append("")

    # -- hardware ---------------------------------------------------------
    topology = "heterogeneous" if cpu.is_heterogeneous else "uniform"
    clusters = ", ".join(f"{c.physical_cores}× {c.core_name or c.name}" for c in cpu.clusters)
    sve = f"{cpu.sve_vector_bits}-bit" if cpu.sve_vector_bits else "not implemented"
    sme = f"{cpu.sme_vector_bits}-bit" if cpu.sme_vector_bits else "not implemented"
    lines += [
        "## The machine this was measured on",
        "",
        "| | |",
        "| --- | --- |",
        f"| CPU | {cpu.model} ({cpu.architecture}) |",
        f"| Cores | {cpu.physical_cores} physical, {topology} — {clusters} |",
        f"| Arm features | {', '.join(sorted(cpu.features)) or 'none detected'} |",
        f"| SVE | {sve} |",
        f"| SME | {sme} |",
        f"| Memory | {report.host.total_memory_gb:.1f} GB |",
        f"| OS | {report.host.os_name} {report.host.os_release} |",
        "",
        "**This recommendation is specific to this CPU.** A different Arm chip "
        "with a different core topology or a different instruction set will "
        "have a different answer — that is the entire premise of the tool. "
        "Rerun `armforge optimize` on the machine you intend to deploy to.",
        "",
    ]

    # -- files ------------------------------------------------------------
    lines += [
        "## What is in this package",
        "",
        "| File | Contents |",
        "| --- | --- |",
        "| `config.json` | The winning configuration, machine-readable |",
        "| `benchmark.json` | Every candidate measured, with full provenance |",
        "| `report.html` | Self-contained report with charts — open it directly |",
        "| `run.sh` | Runs the model with the measured configuration |",
        "| `Dockerfile` | Reproduces the exact build and flags on Arm64 |",
        "",
        "The model file is **not** included. It is referenced by path and "
        "content hash so the package stays small and you can verify you have "
        "the same weights the measurements describe.",
        "",
        "## Running it",
        "",
        "```bash",
        './run.sh -p "your prompt here"',
        "```",
        "",
        "Set `ARMFORGE_MODEL` if the model lives elsewhere, and `LLAMA_BIN` if "
        "your llama.cpp binary is not on `PATH`.",
        "",
        "### In a container",
        "",
        "```bash",
        "docker build --platform linux/arm64 -t armforge-inference .",
        'docker run --rm -v /path/to/models:/models armforge-inference -p "hello"',
        "```",
        "",
        "The image pins the same llama.cpp commit and build flags that were "
        "measured. Note that containerising does not itself make inference "
        "faster — the gains come from the quantisation, build and thread "
        "choices recorded here.",
        "",
        "## Reproducing the measurements",
        "",
        "```bash",
        "pip install armforge",
        "scripts/setup-llama-cpp.sh",
        f"armforge optimize {Path(config.model.path).name} "
        f"--workload {config.workload.name} --iterations {config.iterations}",
        "```",
        "",
        "## What these numbers are not",
        "",
        "- **Not a quality claim.** Throughput only. A faster quantisation is "
        "not automatically a better one, and different quantisations do not "
        "produce identical output.",
        "- **Capability is not usage.** Detecting an Arm extension proves the "
        "silicon has it, not that the runtime used it. The ggml feature flags "
        "actually compiled into the build are recorded in `benchmark.json`.",
        "- **One machine, one model.** Results transfer only as far as the "
        "hardware and model do.",
        "",
    ]
    return "\n".join(lines) + "\n"


def export_package(
    report: SweepReport,
    recommendation: Recommendation,
    out_dir: Path,
    *,
    hash_limit: int | None = 256 * 1024 * 1024,
) -> list[Path]:
    """Write a complete deployment package. Returns the files created."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    model_path = Path(recommendation.winner.result.config.model.path)
    model_hash = (
        content_hash(model_path, max_bytes=hash_limit) if model_path.is_file() else None
    )

    written: list[Path] = []

    def write(name: str, text: str, *, executable: bool = False) -> None:
        path = out_dir / name
        path.write_text(text)
        if executable:
            path.chmod(0o755)
        written.append(path)

    write("config.json", json.dumps(_config(report, recommendation, model_hash), indent=2))

    payload = report.to_dict()
    payload["recommendation"] = recommendation.to_dict()
    write("benchmark.json", json.dumps(payload, indent=2))

    write("report.html", html_report.render(report, recommendation))
    write("README.md", _readme(report, recommendation, model_hash))
    write("run.sh", _run_script(recommendation), executable=True)
    write("Dockerfile", _dockerfile(report, recommendation))

    return written
